### ISSUE TITLE
Acceleration structure crashes

### ISSUE THREAD

**Issue by peterstace** [peterstace/grayt#13]
Example:

```
package main

import (
	. "github.com/peterstace/grayt/examples/cornellbox"
	. "github.com/peterstace/grayt/grayt"
)

func scene() Scene {
	const d = 1.3
	const gap = 0.05
	return Scene{
		Camera: Cam(d),
		Objects: Group(
			Floor,
			Ceiling,
			CeilingLight().With(Emittance(5.0)),
			AlignedSquare(Vect(-10, -10, d), Vect(10, 10, d)),
		),
	}
}

func main() {
	Run("cornellbox_mirrors", scene())
}
```

**Comment by peterstace** [comment]
```
 $ go run examples/cornellbox/mirrors/main.go -q 5 && mv *.png /vagrant/grayt/
panic: runtime error: index out of range

goroutine 5 [running]:
panic(0x4ef4c0, 0xc4200100f0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/peterstace/grayt/grayt.(*grid).populate(0xc420080180, 0xc4200180e0, 0x4, 0x4)
        /home/vagrant/go/src/github.com/peterstace/grayt/grayt/grid.go:60 +0x3e5
github.com/peterstace/grayt/grayt.newGrid(0x4010000000000000, 0xc4200180e0, 0x4, 0x4, 0x64000)
        /home/vagrant/go/src/github.com/peterstace/grayt/grayt/grid.go:34 +0x2fd
github.com/peterstace/grayt/grayt.TraceImage(0x280, 0x3fe0000000000000, 0x3fe0000000000000, 0x3ff4cccccccccccd, 0x3fe0000000000000, 0x3fe0000000000000, 0xbfe0000000000000, 0x0, 0x3ff0000000000000, 0x0, ...)
        /home/vagrant/go/src/github.com/peterstace/grayt/grayt/tracer.go:16 +0x1ed
github.com/peterstace/grayt/grayt.Run.func1(0xc4200560c0, 0xc420088000, 0xc420010628)
        /home/vagrant/go/src/github.com/peterstace/grayt/grayt/run.go:44 +0xa2
created by github.com/peterstace/grayt/grayt.Run
        /home/vagrant/go/src/github.com/peterstace/grayt/grayt/run.go:45 +0x1c1
exit status 2
```

**Comment by peterstace** [comment]
Fixed
